# Generated by Django 5.2.8 on 2025-11-18 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemventa',
            options={'ordering': ['id'], 'verbose_name': 'ItemVenta', 'verbose_name_plural': 'ItemVentas'},
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
