# Generated by Django 5.2.8 on 2025-11-16 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('dni', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000), django.core.validators.MaxValueValidator(60000000)], verbose_name='DNI')),
                ('telefono', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='Teléfono')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido'],
            },
        ),
    ]
